[tool.poetry.dependencies]
python = "^3.7"
selenium = "==3.141.0"
future = "*"
webdriver-manager = "*"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
pylint = "^2.7.0"
pytest = "*"
pytest-cov = "*"
codecov = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
target-version = ['py37']
skip-string-normalization = 1
